### PR TITLE
Remove missing file inclusion.

### PR DESCRIPTION
**Pull request by sepehr**

### CODE REVIEW

**Comment by mrbellek** [comment]
Already fixed in another commit that hasn't been pushed.

**Comment by sepehr** [comment]
Oh, that's great. Just wondering why don't you just push it to master? So it won't throw a fatal error on user's first try.

**Comment by mrbellek** [comment]
Because I forgot? Jeez guy.

**Comment by sepehr** [comment]
No offense buddy just wanted to know. Take it easy.

**Comment by mrbellek** [comment]
Whoops, my bad - hadn't committed this yet. Pushed in 72ba7ea4a661289038754efe79c281cb01705f84

**Pull request closed without merging**
